### ISSUE TITLE
How to generate reading order?

### ISSUE THREAD

**Issue by f771216203** [dell-research-harvard/HJDataset#2]
I have read the paper, but I can understand  how to searching the large gaps between blocks to identify the discontinuity and correct the special reading order accord ingly?
Is there the same method to get the order of index image and main image?

**Comment by lolipopshock** [comment]
Sorry for the late response - I just was your issue post. 

For the 2nd question, yes, we used a similar method, i.e., ordering the blocks generally based on a right-to-left ordering schema. 

For the 1st question, were you asking how to identify the reading order based on the gaps?
